import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
const poppins = Poppins({
  weight: "500",
  variable: "--font-poppins-sans",
  subsets: ["latin"],
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable}  h-full antialiased`}>
      <body className="">{children}</body>
    </html>
  );
}
